mysql:
  host:"127.0.0.1"
  port:3306
  user:"root"
  password:"root"
  dbname:"blog"
  log_level:dev
system:
  host:"0.0.0.0"
  port:8080
  env:dev
logger:
  level:info
  prefix:"[blog]"
  directory:log
  show_line:true
  log_in-console:true